---
#https://github.com/jadebustos/devopslabs/blob/master/labs-k8s/03-desplegando-routed-application.md
- name: Namespace
#  kubernetes.core.k8s:
#    name: argo
#    api_version: v1
#    kind: Namespace
#    state: present
  command: 'kubectl create namespace webapp-routed'
  register: result
  become: true
  become_method: sudo

- debug:
    msg: '{{ result }}'
