---
#Configuramos el firewall para acceder a los servicios de kubernetes:
- name: 'puertos de servicios kubernetes'
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ ports_workers }}'
  become: true
  become_method: sudo

- name: restart firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  become_method: sudo

- name: Habilito ip workers
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ item }} accept'
    permanent: yes
    state: enabled
  loop: '{{ workers_ips }}'
  become: true
  become_method: sudo

- name: Habilito ip para docker
  firewalld:
    rich_rule: 'rule family=ipv4 source address=172.17.0.0/16 accept'
    permanent: yes
    state: enabled
  become: true
  become_method: sudo

#- name: restart firewalld
#  systemd:
#    name: firewalld
#    state: reload
#  become: true
#  become_method: sudo

- name: Reiniciamos el servicio de firewall
  command: systemctl restart firewalld
  register: result
  become: true
  become_method: sudo

- name: restart docker
  systemd:
    name: 'docker'
    state: reloaded
  become: true
  become_method: sudo


- name: Obtengo las imagenes de Kubeadmn
  command: systemctl restart docker
  register: result
  become: true
  become_method: sudo


- name: Espera 30 segundos - Reinicia dockers
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: true
  become_method: sudo