---
- name: Listo las imagenes de kubeadm
  command: kubeadm config images list
  become: true
  become_method: sudo


- name: Obtengo las imagenes de Kubeadmn
  command: kubeadm config images pull
  register: result
  become: true
  become_method: sudo

- debug:
    msg: 'Pull imagenes: {{ result }}'

#Instalamos el plugin CNI (Container Network Interface) de kubernetes y
# definimos la red de los PODs:
- name: Container Network Interface
  command: 'kubeadm init --pod-network-cidr {{ master_range_ip }}'
  register: result2
  become: true
  become_method: sudo

- debug:
    msg: '{{ result2 }}'