---

- name: "install {{ item }}"
  firewalld:
    service: '{{ item }}'
    permanent: yes
    state: enabled
  loop: '{{ list_service }}'
  become: true
  become_method: sudo

- name: restart firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  become_method: sudo