---

- name: "instalar {{ item }}"
  firewalld:
    service: '{{ item }}'
    permanent: yes
    state: enabled
  loop: '{{ list_service }}'
  become: yes
  become_method: sudo


- name: Reiniciamos el servicio de firewall
  systemd:
    name: firewalld
    state: reloaded
  become: yes
  become_method: sudo