---
- name: 'DEBUG - paquetes a instalar'
  debug:
    msg: 'Instalacion de docker'

- name: Downlaod packages
  get_url:
    url: '{{ item.repo_url | mandatory}}'
    dest: '{{ item.repo_dest | mandatory}}'
  #when: 'repo_url is defined and repo_dest  is defined'
  loop: '{{ repos | mandatory }}'
  become: true
  become_method: sudo
  
- name: 'instalo docker ce'
  dnf:
    name: 'docker-ce'
    state: present
  become: true
  become_method: sudo

- name: 'Inicializa servicio y setea inicio automatico para servicio docker'
  systemd:
    name: 'docker'
    state: started
    enabled: yes
  become: true
  become_method: sudo

- name: 'Copio archivo para config daemon.json'
  copy:
    src: 'daemon.json'
    dest: '/etc/docker/'
  become: true
  become_method: sudo

- name: Reiniciamos el servicio de docker
  systemd:
    name: 'docker'
    state: reloaded
  become: true
  become_method: sudo