---
- name: 'DEBUG - paquetes a instalar'
  debug:
    msg: 'Instalacion de Kubernetes'

- name: 'Copio archivo para config repo | kubernetes.repo'
  copy:
    src: 'kubernetes.repo'
    dest: '/etc/yum.repos.d/'
  become: yes
  become_method: sudo
  
- name: 'instalo los paquete kubelet,kubeadm,kubectl'
  dnf:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes
    state: present
  become: yes
  become_method: sudo

- name: 'Inicializa servicio y setea inicio automatico para servicio kubelet'
  systemd:
    name: 'kubelet'
    state: started
    enabled: yes
  become: yes
  become_method: sudo
