---
#https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- name: Namespace
  k8s: 
    name: argo
    api_version: v1
    kind: Namespace
    state: present
  become: true
  become_method: sudo
