---
- name: Set TimeZone
  timezone:
    name: '{{ timezone_name }}' #defaults
  become: true
  become_method: sudo

- name: Install Chrony
  dnf:
    name: chrony
    state: present
    update_cache: yes
  become: true
  become_method: sudo

- name: enable chronyd
  #command: systemctl enable firewalld
  service:
       name: chronyd
       state: started
       enabled: True
  #systemd:
  #  name: firewalld
  #  daemon_reload: yes
  #  state: started
  #  enabled: yes
  become: true
  become_method: sudo

- name: Start Chrony
  #command: systemctl enable chronyd
  #service:
  #    name: chronyd
  #    state: started #reloaded, restarted, started, stopped
  #    enabled: True
  ansible.builtin.systemd:
    daemon_reload: no
    state: started
    name: chronyd
    enabled: yes
  become: true
  become_method: sudo

- name: Timedatectl
  command: timedatectl set-ntp true
  become: true
  become_method: sudo
