---
- name: Update hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}.*$'
    line: '{{ item.ip }} {{ item.name }} {{ item.name_long }}'
    state: present
    backup: no
  with_items: "{{ hosts }}"
  become: true
  become_method: sudo
#- name: "add the correct search entry in /etc/resolv.conf"
#  lineinfile:
#    path: /etc/resolv.conf
#    regexp: '^search'
#    line: 'search silgonza.ar'
#  become: true
#  become_method: sudo

#- name: "update the peerdns in ifcfg-eth0"
#  lineinfile:
#    path: /etc/sysconfig/network-scripts/ifcfg-eth0
#    regexp: '^PEERDNS'
#    line: 'PEERDNS=no'
#  become: true
#  become_method: sudo

#- name: "add entry in /etc/resolv.conf"
#  lineinfile:
#    path: /etc/resolv.conf
#    regexp: '^nameserver'
#    line: 'nameserver 8.8.8.8'
#  become: true
#  become_method: sudo

#- name: "add entry in ifcfg-eth0"
#  lineinfile:
#    path: /etc/sysconfig/network-scripts/ifcfg-eth0
#    regexp: '^DNS1'
#    line: 'DNS1=8.8.8.8'
#  become: true
#  become_method: sudo