---
- name: Update hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}.*$'
    line: '{{ item.ip }} {{ item.name }} {{ item.name_long }}'
    state: present
    backup: no
  with_items: "{{ hosts }}"
  become: true
  become_method: sudo
