---

- name: install firewall
  dnf:
    name: firewalld
    state: present
    update_cache: yes
  register: result
  become: true
  become_method: sudo

- name: inactive AllowZoneDrifting
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: 'AllowZoneDrifting.*'
    line: 'AllowZoneDrifting=no'
    state: present
  become: true
  become_method: sudo

- name: enable firewall
  #command: systemctl enable firewalld
  service:
       name: firewalld
       state: started
       enabled: True
  #systemd:
  #  name: firewalld
  #  daemon_reload: yes
  #  state: started
  #  enabled: yes
  become: true
  become_method: sudo

- name: start firewall
  #command: systemctl start firewalld
  systemd:
    name: firewalld
    daemon_reload: no
    state: started
  become: true
  become_method: sudo