---

- name: 'Configura los puertos para el worker'
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ ports_workers }}'
  become: true
  become_method: sudo

- name: restart firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  become_method: sudo