---

- hosts: workers
  #strategy: debug
  vars_files:
    - 'group_vars/kube.yaml'
    - 'group_vars/v_host.yaml'
  gather_facts: false
  roles:
    #- role: prerequisites
    - role: init_k8snodes
      vars:
        swap_status: 'no'
    - role: init_workers
