---
#https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- name: Namespace
#  kubernetes.core.k8s:
#    name: argo
#    api_version: v1
#    kind: Namespace
#    state: present
  command: 'kubectl create namespace argocd'
  register: result
  become: true
  become_method: sudo

- debug:
    msg: '{{ result }}'
